apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-bot
  template:
    metadata:
      labels:
        app: sso-bot
    spec:
      containers:
        - name: sso-bot
          image: basicbotacr.azurecr.io/sso-bot
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: dev-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: sso-bot
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: sso-bot
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <email>
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-bot-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    - <host>
    secretName: tls-secret
  rules:
    - host: <host>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sso-bot
                port:
                  number: 80
